name: "📁Unzip and Deploy new tiles🚀"

on:
  push:
    branches: [ main ]
jobs:
  deploy_new_tiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./tiles_to_add/*.zip"


      - name: Extract tiles on server
        uses: garygrossgarten/github-action-ssh@release
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          command:  python tile_zip_grabber.py ${{secrets.GH_TOKEN}}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
        env:
          CI: true
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'albertkun'
          repository: 'ucla_maapp_tiles_deploy'
      - name: Access cloned repository content
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          cd ucla_maapp_tiles_deploy
          mv tiles_to_add/*zip existing_tiles/
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .      
          git commit -am '[Auto] Moved tiles_to_add to existing_tiles'
          git push
